#!/bin/bash

set -o errexit
set -o nounset

echo "Starting Celery worker..."


python -c "import app.tasks.dataset_tasks; print('Task modules imported and registered successfully.')"



exec celery -A app.core.celery_app worker \
    --loglevel=${LOG_LEVEL:-INFO} \
    -Q ${CELERY_QUEUE:-dataset_impacts} \
    --concurrency=${WORKER_CONCURRENCY:-10} \
    --pool=prefork \
    -E \
    --include=app.tasks.dataset_tasks