#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Wait for Redis to be ready before starting services
redis_ready() {
    redis-cli -h redis -p 6379 ping | grep PONG
}

echo "Waiting for Redis to be ready..."
until redis_ready; do
  >&2 echo 'Redis is unavailable - sleeping'
  sleep 1
done
>&2 echo 'Redis is up - continuing...'

# Execute the command
exec "$@" 